[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
pyloid = "^0.20.1"
pyinstaller = "^6.11.1"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.32.1"
black = "^24.10.0"

[tool.poe.tasks]
dev = "python ./src-pyloid/main.py"
build = "python ./build.py"

[tool.black]
line-length = 92
target-version = ["py36", "py37", "py38"]
skip-string-normalization = true

[tool.pyright]
venvPath = "./"
venv = ".venv"
pythonVersion = "3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
